---

- name: Run command on BIG-IP
  hosts: bigipa
  connection: local

  tasks:
    - name: run show version on remote devices
      bigip_command:
        commands: show sys version
        server: bigipa
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
      delegate_to: localhost
