---

- name: Run command on BIG-IP
  hosts: all
  connection: local

  tasks:
    - name: tmsh show sys version
      bigip_command:
        commands: tmsh show sys version
        provider: "{{ login_info }}"
      delegate_to: localhost
      register: tmsh

    - debug:
        var: tmsh.stdout_lines
