---

- name: Run command on BIG-IP
  hosts: all
  connection: local

  tasks:
    - name: run show version on remote devices
      bigip_command:
        server: "{{ inventory_hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
        commands: tmsh show sys version
        validate_certs: no 
      delegate_to: localhost
