---

- name: Install AS3 RPM
  hosts: new-bigip
  connection: local
  gather_facts: false

  vars_prompt:
  - name: "username"
    default: "admin"
    prompt: "username"
    private: no
  - name: "password"
    default: "admin"
    prompt: "passwd"
    private: yes

  tasks:
  - name: Install AS3 RPM
    bigip_iapplx_package:
      package: f5-appsvcs-3.8.0-3.noarch.rpm
      state: present
      provider: "{{ login_info }}"
    delegate_to: localhost
