---

- name: License a BIG-IP
  hosts: new-bigip
  connection: local

  tasks:
    - name: License BIG-IP
      bigip_device_license:
        license_key: "{{ key }}"
        accept_eula: yes
        provider: "{{ login_info }}"
      delegate_to: localhost
