---

- name: License a BIG-IP
  hosts: new-bigip
  connection: local

  tasks:
    - name: License BIG-IP using a key
      bigip_license:
        key: "{{ key }}"
        provider: "{{ login_info }}"
      delegate_to: localhost
