---

- name: Provision a new BIG-IP
  hosts: new-bigip
  connection: local

  tasks:
    - name: License BIG-IP
      bigip_device_license:
        license_key: "{{ key }}"
        accept_eula: yes
        provider: "{{ login_info }}"
      delegate_to: localhost

    - name: Disable GUI setup
      bigip_sys_global:
        gui_setup: no
        state: present
        provider: "{{ login_info }}"
      delegate_to: localhost

    - name: Set the hostname of the BIG-IP
      bigip_hostname:
        hostname: "{{ host }}.lab.local"
        provider: "{{ login_info }}"
      delegate_to: localhost

    - name: Create Internal VLAN
      bigip_vlan:
        name: "internal"
        untagged_interfaces: "1.2"
        provider: "{{ login_info }}"
      delegate_to: localhost

    - name: Create Internal Self IP
      bigip_selfip:
        vlan: "internal"
        name: "internal"
        address: "10.2.2.3"
        netmask: "255.255.255.0"
        provider: "{{ login_info }}"
      delegate_to: localhost

    - name: Create External VLAN
      bigip_vlan:
        name: "external"
        untagged_interfaces: "1.1"
        provider: "{{ login_info }}"
      delegate_to: localhost

    - name: Create External Self IP
      bigip_selfip:
        name: "external"
        vlan: "external"
        address: "10.1.1.3"
        netmask: "255.255.255.0"
        provider: "{{ login_info }}"
      delegate_to: localhost

    - name: Provision LTM
      bigip_provision:
        module: ltm
        level: nominal
        provider: "{{ login_info }}"
      delegate_to: localhost

    - name: Provision AVR
      bigip_provision:
        module: avr
        level: nominal
        provider: "{{ login_info }}"
      delegate_to: localhost
