---

- name: Provision a new BIG-IP
  hosts: new-bigip
  connection: local
  gather_facts: false

  vars_prompt:
  - name: "username"
    default: "admin"
    prompt: "username"
    private: no
  - name: "password"
    default: "admin"
    prompt: "passwd"
    private: yes
  - name: "key"
    prompt: "reg key"
    private: no
  - name: "host"
    default: "bigipa"
    prompt: "host name"
    private: no
  - name: "internal_self"
    default: "10.2.2.3"
    prompt: "internal self-ip"
    private: no
  - name: "external_self"
    default: "10.1.1.3"
    prompt: "external self-ip"
    private: no

  tasks:
    #- import_tasks: license_big-ip.yml
    #- import_tasks: disable_setup.yml
    #- import_tasks: name_big-ip.yml
    - import_tasks: configure_self-ips.yml
    - import_tasks: install_as3.yml
    - import_tasks: provision_modules.yml
