---
- name: Create the Hackazon VIP, pool, pool members and nodes
  hosts: ltm1
  connection: local

  vars_prompt:
  - name: "username"
    default: "admin"
    prompt: "username"
    private: no
  - name: "password"
    default: "admin"
    prompt: "passwd"
    private: yes

  tasks:
      - name: Create the Hackazon pool
        bigip_pool:
            name: "hackazon_pool"
            slow_ramp_time: "120"
            lb_method: least-connections-node
            monitor_type: and_list
            monitors: http
            provider: "{{ login_info }}"
        delegate_to: localhost

      - name: Create the Hackazon node 1
        bigip_node:
            host: "10.1.20.200"
            name: "hackazon_node1"
            provider: "{{ login_info }}"
        delegate_to: localhost

      - name: Create the Hackazon node 2
        bigip_node:
            host: "10.1.20.201"
            name: "hackazon_node2"
            provider: "{{ login_info }}"
        delegate_to: localhost

      - name: Add the Hackazon node to pool
        bigip_pool_member:
            description: "hackazon_pool"
            host: "{{ item.host }}"
            name: "{{ item.name }}"
            pool: "hackazon_pool"
            port: "80"
            provider: "{{ login_info }}"
        delegate_to: localhost
        with_items:
            - host: "10.1.20.200"
              name: "hackazon_node1"
            - host: "10.1.20.201"
              name: "hackazon_node2"

      - name: Create the Hackazon VIP
        bigip_virtual_server:
            description: "hackazon_vs"
            destination: "10.1.10.200"
            name: "hackazon_vs"
            pool: "hackazon_pool"
            port: "80"
            snat: "Automap"
            all_profiles:
                - "http"
            provider: "{{ login_info }}"
        delegate_to: localhost
