- name: Add DCD devices to CM device concurrently
  hosts: dcd
  vars_files:
    - vars/main.yml
  tasks:
    - name: Add DCD to CM
      include_role:
        name: f5devcentral.register_dcd
      vars:
        register_dcd_dcd_server: "{{ ansible_host }}"