- name: Create node1
  bigip_node:
      host: 10.10.10.10
      name: node-1
      password: admin
      server: big-ip01.internal
      user: admin
      validate_certs: no
  delegate_to: localhost

- name: Create node2
  bigip_node:
      host: 10.10.10.20
      name: node-2
      password: admin
      server: big-ip01.internal
      user: admin
      validate_certs: no
  delegate_to: localhost