---

- name: Run command on BIG-IP
  hosts: bigipa
  connection: local

  tasks:
    - name: tmsh show sys version
      bigip_command:
        commands: show sys version
        server: bigipa
        password: admin
        user: admin
        validate_certs: no
      delegate_to: localhost
      register: show

    - debug: 
        var: show.stdout_lines
