---

- name: Create the Hackazon VIP, pool, pool members and nodes
  hosts: new-bigip
  connection: local

  tasks:
      - name: Create the Hackazon pool
        bigip_pool:
            name: "hackazon_pool"
            slow_ramp_time: "120"
            lb_method: least-connections-node
            monitor_type: and_list
            monitors: http
            provider: "{{ login_info }}"
        delegate_to: localhost

      - name: Create the Hackazon node
        bigip_node:
            host: "10.1.20.20"
            name: "hackazon_node"
            provider: "{{ login_info }}"
        delegate_to: localhost

      - name: Create the Hackazon node 2
        bigip_node:
            host: "10.1.20.21"
            name: "hackazon_node2"
            provider: "{{ login_info }}"
        delegate_to: localhost

      - name: Add the Hackazon node to pool
        bigip_pool_member:
            description: "hackazon_pool"
            host: "{{ item.host }}"
            name: "{{ item.name }}"
            pool: "hackazon_pool"
            port: "80"
            provider: "{{ login_info }}"
        delegate_to: localhost
        with_items:
            - host: "10.1.20.20"
              name: "hackazon_node"
            - host: "10.1.20.21"
              name: "hackazon_node"

      - name: Create the Hackazon VIP
        bigip_virtual_server:
            description: "hackazon_vs"
            destination: "10.1.10.20"
            name: "hackazon_vs"
            pool: "hackazon_pool"
            port: "80"
            snat: "Automap"
            all_profiles:
                - "http"
            provider: "{{ login_info }}"
        delegate_to: localhost
