---
- name: Save config on BIG-IP(s)
  hosts: gtms
  connection: local
  gather_facts: false

  vars_prompt:
  - name: 'username'
    default: 'admin'
    prompt: 'BIG-IP username'
    private: no
  - name: 'password'
    default: 'admin'
    prompt: 'BIG-IP passwd'
    private: yes

  tasks:
  - name: Save the running configuration of the BIG-IP
    bigip_config:
      provider: '{{ login_info }}'
      save: yes
    delegate_to: localhost
