---
- name: Upload qkview file(s) to iHealth
  hosts: localhost
  connection: local
  gather_facts: false

  vars_prompt:
  - name: 'user_id'
    default: 'root@localhost.localdomain'
    prompt: 'iHealth username'
    private: no
  - name: 'user_secret'
    default: 'default'
    prompt: 'iHealth passwd'
    private: yes


  tasks:
  - name: Uploading qkview to iHealth
    uri:
      url: https://api.f5.com/auth/pub/sso/login/ihealth-api
      src: 'big-ip.qkview'
      method: POST
      return_content: true
      user: '{{ user_id }}'
      password: '{{ user_secret }}'
      force_basic_auth: true
      status_code: 201
      validate_certs: no
      headers:
        User-Agent: FSE_QKapi
        Content-Type: application/json
    delegate_to: localhost

  - debug: msg='{{ http_response }}'