---
- name: Create and download a qkview from a BIG-IP(s)
  hosts: bigip
  connection: local
  gather_facts: false

  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M-') }}"

  tasks:
  - name: Downloading qkview from '{{ inventory_hostname }}'
    bigip_qkview:
      provider: '{{ login_info }}'
      asm_request_log: no
      exclude:
        - audit
        - secure
      filename: "{{ inventory_hostname + '.qkview' }}"
      dest: ./files/{{ date + inventory_hostname + '.qkview' }}
      force: yes
    delegate_to: localhost
