---
- name: Create and download a qkview from a BIG-IP(s)
  hosts: all
  connection: local
  gather_facts: false

  vars_prompt:
  - name: 'username'
    default: 'admin'
    prompt: 'BIG-IP username'
    private: no
  - name: 'password'
    default: 'admin'
    prompt: 'BIG-IP passwd'
    private: yes

  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M-') }}"

  tasks:
  - name: Downloading qkview from '{{ inventory_hostname }}'
    bigip_qkview:
      provider: '{{ login_info }}'
      asm_request_log: no
      exclude:
        - audit
        - secure
      filename: "{{ inventory_hostname + '.qkview' }}"
      dest: ./files/{{ date + inventory_hostname + '.qkview' }}
      force: yes
    delegate_to: localhost
