---
- name: Run a command on BIG-IP(s)
  hosts: gtm
  connection: local
  gather_facts: false

  tasks:
  - name: Running '{{ tmsh_command }}' on '{{ inventory_hostname }}'
    bigip_command:
      provider: '{{ login_info }}'
      commands:
        - '{{ tmsh_command }}'
    delegate_to: localhost
    register: tmsh

  - debug:
      var: tmsh.stdout_lines
